Repository sloukit/pydew-valley-uzh, pull requests merged in 2024-08, with the labels that each got.

#100 enha(deps): Refactor project dependency handling and configuration files
  .github/workflows/lint-and-test.yml
  .github/workflows/main.yml
  README.md
  pyproject.toml
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  test-requirements.txt
  tox.ini
Labels: area: documentation, type: enhancement, area: ci, area: dependencies, area: code quality

#103 Cosmetic rendering
  .gitignore
  images/characters/rabbit/goggles_axe.png
  images/characters/rabbit/goggles_hoe.png
  images/characters/rabbit/goggles_idle.png
  images/characters/rabbit/goggles_walk.png
  images/characters/rabbit/goggles_water.png
  images/characters/rabbit/hat_axe.png
  images/characters/rabbit/hat_hoe.png
  images/characters/rabbit/hat_idle.png
  images/characters/rabbit/hat_walk.png
  images/characters/rabbit/hat_water.png
  images/characters/rabbit/horn_axe.png
  images/characters/rabbit/horn_hoe.png
  images/characters/rabbit/horn_idle.png
  images/characters/rabbit/horn_walk.png
  images/characters/rabbit/horn_water.png
  images/characters/rabbit/necklace_axe.png
  images/characters/rabbit/necklace_hoe.png
  images/characters/rabbit/necklace_idle.png
  images/characters/rabbit/necklace_walk.png
  images/characters/rabbit/necklace_water.png
  src/enums.py
  src/sprites/entities/player.py
  src/sprites/water_drop.py
  src/support.py
Labels: size: M, type: feature, game-art, priority: high, game-mechanics

#110 Fix settings
  data/save.json
  src/gui/menu/components.py
  src/gui/menu/description.py
  src/screens/level.py
  src/screens/menu_settings.py
Labels: size: S, game-ui, type: bugfix, priority: low

#115 Added features to bathhouse
  src/screens/level.py
Labels: type: enhancement, game-environments, game-mechanics

#119 make berry bushes harvestable
  data/tilesets/trees_and_bushes.tsx
  images/objects/blackberry.png
  images/objects/blueberry.png
  images/objects/raspberry.png
  src/enums.py
  src/screens/game_map.py
  src/screens/level.py
  src/settings.py
  src/sprites/character.py
  src/sprites/objects/berry_bush.py
Labels: type: feature, game-art, game-mechanics

#121 Reimplement time logic
  src/enums.py
  src/overlay/clock.py
  src/overlay/game_time.py
  src/overlay/overlay.py
  src/overlay/sky.py
  src/screens/level.py
Labels: type: enhancement, area: code quality

#113 Camera expansion
  .gitignore
  data/maps/farm_new.tmx
  data/maps/forest.tmx
  main.py
  src/camera/__init__.py
  src/camera/camera.py
  src/camera/camera_target.py
  src/camera/quaker.py
  src/camera/zoom_area.py
  src/camera/zoom_manager.py
  src/controls.py
  src/enums.py
  src/events.py
  src/exceptions.py
  src/groups.py
  src/gui/interface/dialog.py
  src/gui/menu/description.py
  src/gui/scene_animation.py
  src/screens/game_map.py
  src/screens/level.py
  src/sprites/base.py
  src/sprites/drops.py
  src/sprites/entities/entity.py
  src/sprites/entities/player.py
  src/sprites/objects/tree.py
Labels: type: enhancement, game-cinematics

#124 Persistent crops
  data/maps/farm_new.tmx
  data/save.json
  main.py
  src/overlay/soil.py
  src/savefile.py
  src/savefile/__init__.py
  src/savefile/savefile.py
  src/savefile/tile_info.py
  src/screens/game_map.py
  src/screens/level.py
  src/settings.py
  src/sprites/entities/player.py
  src/sprites/objects/berry_bush.py
Labels: type: bugfix, game-mechanics

#129 Volcano anim
  images/animations/smoke_infinite.png
  images/animations/smoke_start.png
  images/animations/volcano.png
  images/animations/volcano_exploding.png
Labels: type: feature, game-art
