Repository sloukit/pydew-valley-uzh, pull requests merged in 2024-07, with the labels that each got.

#32 Button click animation
  .DS_Store
  .gitignore
  data/settings/keybinds.json
  data/settings/volume.json
  images/.DS_Store
  images/characters/.DS_Store
  images/keys/alt.png
  images/keys/down.png
  images/keys/down.svg
  images/keys/generic.png
  images/keys/generic.svg
  images/keys/lclick.png
  images/keys/lctrl.png
  images/keys/left.png
  images/keys/lshift.png
  images/keys/rclick.png
  images/keys/rctrl.png
  images/keys/return.png
  images/keys/right.png
  images/keys/right.svg
  images/keys/rshift.png
  images/keys/space.png
  images/keys/space.svg
  images/keys/tab.png
  images/keys/up.png
  images/keys/up.svg
  main.py
  src/level.py
  src/menus.py
  src/overlay.py
  src/settings.py
  src/sprites.py
  src/support.py
Labels: type: enhancement, game-ui

#41 Removed freezed image with menus
  main.py
  src/level.py
  src/menus.py
  src/sprites.py
Labels: game-ui, type: bugfix

#49 Docs: Add Code of Conduct
  docs/CODE_OF_CONDUCT.md
Labels: area: documentation, type: enhancement

#51 Docs: Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE/code_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/docs_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/pr_revert_template.md
  .github/pull_request_template.md
Labels: area: documentation, type: enhancement

#52 docs: Fix broken links and markdown issues in GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area: documentation, type: enhancement

#53 Folders Architecture
  main.py
  src/groups.py
  src/gui/components.py
  src/gui/description.py
  src/gui/general_menu.py
  src/menus.py
  src/npc/dialog.py
  src/npc/npc.py
  src/npc/npc_behaviour.py
  src/overlay/overlay.py
  src/overlay/sky.py
  src/overlay/soil.py
  src/overlay/transition.py
  src/screens/level.py
  src/screens/menu.py
  src/screens/pause.py
  src/screens/settings.py
  src/screens/shop.py
  src/settings.py
  src/sprites/base.py
  src/sprites/entity.py
  src/sprites/particle.py
  src/sprites/plant.py
  src/sprites/player.py
  src/sprites/tree.py
  src/sprites/water_drop.py
  src/warnings.py
Labels: type: enhancement, area: code quality

#55 Fixed bad filename and missing STL warnings import
  src/import_checks.py
  src/settings.py
Labels: type: enhancement, area: testing, area: code quality, type: bugfix, priority: high

#58 Reimplement NPC setup & code improvements
  src/npc/behaviour_base.py
  src/npc/npc.py
  src/npc/npc_base.py
  src/npc/npc_behaviour.py
  src/screens/level.py
  src/settings.py
  src/sprites/player.py
Labels: game-ai, area: code quality, type: bugfix, priority: high

#54 Soil refacto
  data/.DS_Store
  main.py
  src/.DS_Store
  src/overlay/soil.py
  src/screens/level.py
  src/screens/menu.py
  src/screens/pause.py
  src/screens/settings.py
  src/screens/shop.py
  src/sprites/entity.py
  src/sprites/plant.py
  src/sprites/player.py
  src/support.py
Labels: type: enhancement, area: code quality

#63 added health bar
  images/health_bar/health_bar.png
  images/health_bar/health_cat_1.png
  images/health_bar/health_cat_2.png
  images/health_bar/health_cat_3.png
  main.py
  src/gui/health_bar.py
Labels: type: feature, game-ui

#61 Refactor event handlers
  main.py
  src/controls.py
  src/gui/components.py
  src/gui/description.py
  src/gui/general_menu.py
  src/npc/npc_behaviour.py
  src/overlay/soil.py
  src/screens/level.py
  src/screens/menu_main.py
  src/screens/menu_pause.py
  src/screens/menu_settings.py
  src/screens/shop.py
  src/settings.py
  src/sprites/player.py
Labels: type: enhancement, game-ui, priority: medium

#65 Add Animals
  data/maps/main.tmx
  data/save.json
  data/tilesets/objects.tsx
  images/entities/chicken/idle.png
  images/entities/chicken/walk.png
  images/entities/cow/idle.png
  images/entities/cow/walk.png
  images/objects/chicken.png
  images/objects/cow.png
  main.py
  src/enums.py
  src/npc/__init__.py
  src/npc/bases/__init__.py
  src/npc/bases/animal.py
  src/npc/bases/chicken_base.py
  src/npc/bases/cow_base.py
  src/npc/bases/npc_base.py
  src/npc/behaviour/__init__.py
  src/npc/behaviour/ai_behaviour.py
  src/npc/behaviour/ai_behaviour_base.py
  src/npc/behaviour/ai_behaviour_tree_base.py
  src/npc/behaviour/chicken_behaviour_tree.py
  src/npc/behaviour/cow_behaviour_tree.py
  src/npc/behaviour/cow_flee_behaviour_tree.py
  src/npc/behaviour/npc_behaviour_tree.py
  src/npc/chicken.py
  src/npc/cow.py
  src/npc/npc.py
  src/npc/setup.py
  src/screens/level.py
  src/settings.py
  src/sprites/base.py
  src/sprites/character.py
  src/sprites/entity.py
  src/sprites/plant.py
  src/sprites/player.py
  src/support.py
Labels: type: feature, game-ai, priority: high

#59 Emotes + Emote Wheel
  images/ui/dialog_boxes/tiny_down.png
  images/ui/emotes/sprout_lands/cheer_ani.png
  images/ui/emotes/sprout_lands/cool_ani.png
  images/ui/emotes/sprout_lands/furious_ani.png
  images/ui/emotes/sprout_lands/love_ani.png
  images/ui/emotes/sprout_lands/sad_ani.png
  images/ui/emotes/sprout_lands/sleep_ani.png
  images/ui/emotes/sprout_lands/smile_ani.png
  images/ui/emotes/sprout_lands/wink_ani.png
  images/ui/indicators/entity_focused.png
  images/ui/indicators/entity_focused_big.png
  main.py
  src/controls.py
  src/groups.py
  src/gui/__init__.py
  src/gui/interface/__init__.py
  src/gui/interface/dialog.py
  src/gui/interface/emotes.py
  src/gui/interface/emotes_base.py
  src/gui/interface/indicators.py
  src/gui/menu/__init__.py
  src/gui/menu/components.py
  src/gui/menu/description.py
  src/gui/menu/general_menu.py
  src/gui/setup.py
  src/npc/behaviour/npc_behaviour_tree.py
  src/npc/npc.py
  src/overlay/soil.py
  src/screens/level.py
  src/screens/menu_main.py
  src/screens/menu_pause.py
  src/screens/menu_settings.py
  src/settings.py
  src/sprites/entity.py
  src/sprites/plant.py
  src/sprites/player.py
  src/support.py
Labels: type: enhancement, type: feature, game-ai, priority: medium

#92 Fix Keybinds
  src/controls.py
  src/gui/menu/description.py
  src/sprites/entities/player.py
Labels: type: enhancement, size: S, game-ui, priority: medium

#75 Inventory screen
  data/save.json
  images/checkmark.png
  images/cosmetics.png
  main.py
  src/controls.py
  src/enums.py
  src/events.py
  src/gui/menu/abstract_menu.py
  src/gui/menu/components.py
  src/gui/menu/description.py
  src/gui/menu/general_menu.py
  src/savefile.py
  src/screens/inventory.py
  src/screens/level.py
  src/screens/menu_pause.py
  src/settings.py
  src/sprites/character.py
  src/sprites/entities/player.py
Labels: size: M, type: feature, game-ui, priority: medium
