Repository sloukit/pydew-valley-uzh, pull requests merged in 2024-10, with the labels that each got.

#194 Player task
  images/objects/blanket.png
  images/objects/candy_bar.png
  main.py
  src/controls.py
  src/enums.py
  src/gui/menu/components.py
  src/overlay/fast_forward.py
  src/screens/inventory.py
  src/screens/level.py
  src/screens/player_task.py
  src/sprites/entities/character.py
  src/sprites/entities/player.py
  src/support.py
Labels: game-gameplay, game-mechanics

#207 added scripted sequence: Group gatherings (triggered by ';')
  data/dialogues.json
  data/maps/farm_new.tmx
  src/controls.py
  src/enums.py
  src/gui/interface/emotes.py
  src/npc/npc.py
  src/overlay/fast_forward.py
  src/screens/level.py
  src/settings.py
  src/sprites/entities/player.py
Labels: type: feature, game-ai, game-mechanics

#217 fix(debug-overlays): Fix hitbox and pf overlay sometimes being offset
  src/screens/level.py
  src/screens/minigames/cow_herding.py
Labels: type: bugfix, game-playtesting
