Repository sloukit/pydew-valley-uzh, pull requests merged in 2025-01, with the labels that each got.

#270 Ensure UTF-8 is used on Windows
  main.py
  src/utils.py
Labels: game-ui, type: bugfix

#290 removed the ability to re-assign keybindings in the options menu
  src/screens/menu_settings.py
Labels: game-ui, type: bugfix, type: revert

#291 Watering Tutorial Bugfix
  src/overlay/soil.py
  src/screens/level.py
Labels: type: bugfix

#294 Improvements on Pricing
  src/enums.py
  src/screens/shop.py
Labels: type: enhancement

#295 you can win 200$ or lose 50$ in the minigame
  data/translations/de.txt
  data/translations/en.txt
  src/screens/minigames/cow_herding.py
  src/screens/minigames/cow_herding_overlay.py
Labels: type: enhancement, type: feature

#298 bugfix npc creation in minigame
  src/screens/minigames/cow_herding.py
Labels: type: bugfix
